# config.yml
telegram:
  enabled: false  # Отключаем Telegram в плагине

api:
  enabled: true
  port: 8080
  key: "your-secret-api-key-here"  # Смените на свой ключ

linking:
  code_expiry_minutes: 10